Repository entropyxyz/entropy-core, pull requests merged in 2024-08, with the labels that each got.

#955 New on-chain registration flow
  CHANGELOG.md
  Cargo.lock
  pallets/registry/Cargo.toml
  pallets/registry/src/benchmarking.rs
  pallets/registry/src/lib.rs
  pallets/registry/src/tests.rs
  pallets/registry/src/weights.rs
  runtime/src/weights/pallet_registry.rs
Labels: Bump `spec_version`

#990 Signing flow with derived accounts
  CHANGELOG.md
  Cargo.lock
  crates/client/entropy_metadata.scale
  crates/client/src/client.rs
  crates/client/src/user.rs
  crates/threshold-signature-server/Cargo.toml
  crates/threshold-signature-server/src/helpers/signing.rs
  crates/threshold-signature-server/src/helpers/substrate.rs
  crates/threshold-signature-server/src/signing_client/errors.rs
  crates/threshold-signature-server/src/signing_client/protocol_execution/mod.rs
  crates/threshold-signature-server/src/signing_client/protocol_transport.rs
  crates/threshold-signature-server/src/user/api.rs
  crates/threshold-signature-server/src/user/errors.rs
  crates/threshold-signature-server/src/user/tests.rs
  crates/threshold-signature-server/src/validator/tests.rs
  pallets/registry/src/benchmarking.rs
  pallets/registry/src/lib.rs
  pallets/registry/src/tests.rs
Labels: Bump `spec_version`

#1022 Remove `prune_registration` extrinsic
  CHANGELOG.md
  crates/client/entropy_metadata.scale
  pallets/registry/src/benchmarking.rs
  pallets/registry/src/lib.rs
  pallets/registry/src/tests.rs
  pallets/registry/src/weights.rs
  runtime/src/weights/pallet_registry.rs
Labels: Bump `transaction_version`

#1021 Clean up registration related tests in `pallet-registry`
  crates/threshold-signature-server/src/user/tests.rs
  crates/threshold-signature-server/tests/sign.rs
  crates/threshold-signature-server/tests/sign_eth_tx.rs
  pallets/registry/src/lib.rs
  pallets/registry/src/tests.rs
Labels: Bump `impl_version`

#1025 Remove `confirm_registered` extrinsic
  CHANGELOG.md
  crates/client/entropy_metadata.scale
  crates/threshold-signature-server/src/helpers/tests.rs
  crates/threshold-signature-server/src/user/api.rs
  crates/threshold-signature-server/src/user/errors.rs
  crates/threshold-signature-server/src/user/tests.rs
  node/cli/src/benchmarking.rs
  pallets/registry/src/benchmarking.rs
  pallets/registry/src/lib.rs
  pallets/registry/src/tests.rs
  pallets/registry/src/weights.rs
  runtime/src/lib.rs
  runtime/src/weights/pallet_registry.rs
Labels: Bump `transaction_version`

#1030 Remove old registration flow
  CHANGELOG.md
  crates/client/entropy_metadata.scale
  crates/client/src/client.rs
  crates/client/src/substrate.rs
  crates/client/src/tests.rs
  crates/client/src/user.rs
  crates/test-cli/src/lib.rs
  crates/threshold-signature-server/src/lib.rs
  crates/threshold-signature-server/src/user/api.rs
  crates/threshold-signature-server/src/user/tests.rs
  crates/threshold-signature-server/tests/register_and_sign.rs
  crates/threshold-signature-server/tests/sign_eth_tx.rs
  node/cli/src/chain_spec/dev.rs
  node/cli/src/chain_spec/integration_tests.rs
  node/cli/src/service.rs
  pallets/propagation/src/lib.rs
  pallets/propagation/src/tests.rs
  pallets/registry/src/benchmarking.rs
  pallets/registry/src/lib.rs
  pallets/registry/src/tests.rs
  pallets/registry/src/weights.rs
  runtime/src/weights/pallet_registry.rs
Labels: Breaks API, Bump `spec_version`

#1018 Rotate parent network key takes 2 steps
  crates/client/entropy_metadata.scale
  crates/shared/src/constants.rs
  crates/threshold-signature-server/src/lib.rs
  crates/threshold-signature-server/src/validator/api.rs
  crates/threshold-signature-server/src/validator/tests.rs
  node/cli/src/service.rs
  pallets/propagation/src/lib.rs
  pallets/propagation/src/tests.rs
  pallets/staking/src/lib.rs
Labels: Bump `spec_version`
